version: "3"

services:
  escape:
    container_name: next-app-escape
    image: nextjs-escape
    # Set environment variables based on the .env file
    env_file:
      - .env

    restart: always
    ports:
      #map any available port on LHS
      - 3002:3000

    networks:
      - escape_network
      - nginx_default

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
        #      - ./ollama/.:/code
    pull_policy: always
    restart: always
    networks:
      - escape_network


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  nginx_default:
    name: nginx_default
    external: true
  escape_network:

