---
services:
  escape:
    container_name: next-app-escape
    image: ghcr.io/doozy134/escape:main
    # Set environment variables based on the .env file
    env_file:
      - .env
    restart: always
    ports:
    # Map any available port on LHS
      - 3000:3000
    networks:
      - escape_network
      - nginx_default

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    restart: always
    networks:
      - escape_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  nginx_default:
    external: true
  escape_network:
